/*
 * This file was generated by the Gradle 'init' task.
 */
plugins {
    java
    `maven-publish`
    application
//    kotlin("jvm") version "1.6.10"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo1.maven.org/maven2/")
    }
    maven {
        url = uri("https://maven.aliyun.com/repository/central/")
    }
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
    ivy {
        setUrl("https://archive.eclipse.org/tools/cdt/releases/10.3/cdt-10.3.2/plugins/")
        metadataSources {
            artifact()
        }
        patternLayout {
            artifact("/[organisation].[module]_[revision].[ext]")
        }
    }
}

dependencies {
    implementation(fileTree(mapOf("dir" to "libs", "include" to listOf("*.jar"))))
//    implementation("io.joern:c2cpg_3:1.1.786")
//    implementation("io.shiftleft:c2cpg_2.13:1.3.407")
    implementation("de.fraunhofer.aisec:cpg-core:4.4.2")
//    implementation("de.fraunhofer.aisec:cpg-neo4j:4.4.2")
    implementation("org.jgrapht:jgrapht-core:1.4.0")
    implementation("org.jgrapht:jgrapht-io:1.4.0")
//    implementation("com.github.javaparser:javaparser-core:3.17.0")
//    implementation("com.github.javaparser:javaparser-symbol-solver-core:3.17.0")
//    implementation("commons-cli:commons-cli:1.4")
//    implementation("org.dom4j:dom4j:2.1.3")
    implementation("log4j:log4j:1.2.17")
//    implementation("org.antlr:antlr4:4.6")
//    implementation("org.antlr:antlr4-runtime:4.6")
    implementation("org.jetbrains.kotlin:kotlin-stdlib:1.6.10")
    implementation("org.jetbrains.kotlin:kotlin-reflect:1.6.10")
//    system("com.github.gumtreediff:client:3.0.0-beta2")
//    system("ghaffarian:graphs:2.5.0")
//    system("ghaffarian:nano-logger:1.1")
}

group = "cn.sdrgroup"
version = "1.0-SNAPSHOT"
description = "SCPG"
java.sourceCompatibility = JavaVersion.VERSION_11

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
